Version: 1
jobs:
	build:
		machine: true
		steps:
			- checkout
			- run:
				name: Install Jfrog CLI
				command: 
					curl -fL https://getcli.jfrog.io | sh
					chmod a+x jfrog && sudo mv jfrog /usr/local/bin
      - run
				name: Configure Jfrog CLI
				command: |
					jfrog rt c --user=${ARTIFACTORY_USER} --url=${ARTIFACTORY_URL} --apikey=${ARTIFACTORY_API_KEY} --interactive=false
