version: 2
jobs:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
     # - run:
     #     name: Push to Artifactory
     #     command: |
     #       ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_API_KEY --interactive=false
            
